USE [master]
GO
/****** Object:  Database [BBIBLIO]    Script Date: 14/04/2021 13:45:33 ******/
CREATE DATABASE [BBIBLIO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BBIBLIO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019\MSSQL\DATA\BBIBLIO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BBIBLIO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQL2019\MSSQL\DATA\BBIBLIO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BBIBLIO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BBIBLIO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BBIBLIO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BBIBLIO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BBIBLIO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BBIBLIO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BBIBLIO] SET ARITHABORT OFF 
GO
ALTER DATABASE [BBIBLIO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BBIBLIO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BBIBLIO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BBIBLIO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BBIBLIO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BBIBLIO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BBIBLIO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BBIBLIO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BBIBLIO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BBIBLIO] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BBIBLIO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BBIBLIO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BBIBLIO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BBIBLIO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BBIBLIO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BBIBLIO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BBIBLIO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BBIBLIO] SET RECOVERY FULL 
GO
ALTER DATABASE [BBIBLIO] SET  MULTI_USER 
GO
ALTER DATABASE [BBIBLIO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BBIBLIO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BBIBLIO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BBIBLIO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BBIBLIO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BBIBLIO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BBIBLIO1', N'ON'
GO
ALTER DATABASE [BBIBLIO] SET QUERY_STORE = OFF
GO
USE [BBIBLIO]
GO
/****** Object:  Table [dbo].[BBIBLIO]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BBIBLIO](
	[bbiblio_id] [int] NOT NULL,
	[bbiblio_address] [varchar](512) NOT NULL,
	[bbiblio_president_name] [varchar](256) NOT NULL,
	[bbiblio_email] [varchar](320) NOT NULL,
	[RCS] [varchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[bbiblio_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BOOKS]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BOOKS](
	[book_id] [int] NOT NULL,
	[book_name] [varchar](256) NOT NULL,
	[publishing_date] [date] NOT NULL,
	[ISBN] [varchar](32) NOT NULL,
	[genre] [varchar](45) NOT NULL,
	[synopsis] [varchar](256) NOT NULL,
	[book_image] [varchar](256) NOT NULL,
	[book_pdf] [varchar](256) NOT NULL,
	[state] [varchar](28) NOT NULL,
	[clicks] [int] NOT NULL,
	[season_id] [int] NOT NULL,
	[category_id] [int] NOT NULL,
	[person_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[book_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CATEGORY]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[category_id] [int] NOT NULL,
	[category_name] [varchar](45) NOT NULL,
	[category_description] [varchar](256) NOT NULL,
	[category_update] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[category_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CRITERIA]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CRITERIA](
	[criterion_id] [int] NOT NULL,
	[criterion_name] [varchar](45) NOT NULL,
	[criterion_description] [varchar](256) NOT NULL,
	[criterion_update] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[criterion_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPEND]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPEND](
	[season_id] [int] NOT NULL,
	[category_id] [int] NOT NULL,
	[criterion_id] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FONCTIONS]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FONCTIONS](
	[fonction_id] [int] NOT NULL,
	[fonction_name] [varchar](50) NOT NULL,
	[fonction_description] [varchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[fonction_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NEWS]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NEWS](
	[news_id] [int] NOT NULL,
	[publication_date] [date] NOT NULL,
	[registration_date] [date] NOT NULL,
	[update_date] [date] NOT NULL,
	[new_texts] [varchar](50) NOT NULL,
	[images] [varchar](256) NULL,
	[person_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[news_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTE]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTE](
	[note_id] [int] null,
	[person_id] [int] NOT NULL,
	[book_id] [int] NOT NULL,
	[criterion_id] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTICIPATE]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTICIPATE](
	[person_id] [int] NOT NULL,
	[season_id] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONS]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONS](
	[person_id] [int] NOT NULL,
	[civility] [varchar](32) NOT NULL,
	[last_name] [varchar](256) NOT NULL,
	[first_name] [varchar](45) NOT NULL,
	[birthday] [date] NOT NULL,
	[publishing_house] [varchar](256) NOT NULL,
	[email] [varchar](320) NOT NULL,
	[phone_number] [varchar](32) NOT NULL,
	[address_1] [varchar](256) NOT NULL,
	[address_2] [varchar](256) NOT NULL,
	[zip_code] [varchar](16) NOT NULL,
	[city] [varchar](128) NOT NULL,
	[country] [varchar](128) NOT NULL,
	[validated_charter] [bit] NOT NULL,
	[validated_charter_date] [date] NOT NULL,
	[person_update_date] [date] NOT NULL,
	[password] [varchar](256) NOT NULL,
	[fonction_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[person_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEASONS]    Script Date: 14/04/2021 13:45:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEASONS](
	[season_id] [int] NOT NULL,
	[season_start] [date] NOT NULL,
	[season_end] [date] NOT NULL,
	[season_description] [varchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[season_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOOKS]  WITH CHECK ADD FOREIGN KEY([category_id])
REFERENCES [dbo].[CATEGORY] ([category_id])
GO
ALTER TABLE [dbo].[BOOKS]  WITH CHECK ADD FOREIGN KEY([person_id])
REFERENCES [dbo].[PERSONS] ([person_id])
GO
ALTER TABLE [dbo].[BOOKS]  WITH CHECK ADD FOREIGN KEY([season_id])
REFERENCES [dbo].[SEASONS] ([season_id])
GO
ALTER TABLE [dbo].[DEPEND]  WITH CHECK ADD FOREIGN KEY([category_id])
REFERENCES [dbo].[CATEGORY] ([category_id])
GO
ALTER TABLE [dbo].[DEPEND]  WITH CHECK ADD FOREIGN KEY([criterion_id])
REFERENCES [dbo].[CRITERIA] ([criterion_id])
GO
ALTER TABLE [dbo].[DEPEND]  WITH CHECK ADD FOREIGN KEY([season_id])
REFERENCES [dbo].[SEASONS] ([season_id])
GO
ALTER TABLE [dbo].[NEWS]  WITH CHECK ADD FOREIGN KEY([person_id])
REFERENCES [dbo].[PERSONS] ([person_id])
GO
ALTER TABLE [dbo].[NOTE]  WITH CHECK ADD FOREIGN KEY([book_id])
REFERENCES [dbo].[BOOKS] ([book_id])
GO
ALTER TABLE [dbo].[NOTE]  WITH CHECK ADD FOREIGN KEY([criterion_id])
REFERENCES [dbo].[CRITERIA] ([criterion_id])
GO
ALTER TABLE [dbo].[NOTE]  WITH CHECK ADD FOREIGN KEY([person_id])
REFERENCES [dbo].[PERSONS] ([person_id])
GO
ALTER TABLE [dbo].[PARTICIPATE]  WITH CHECK ADD FOREIGN KEY([person_id])
REFERENCES [dbo].[PERSONS] ([person_id])
GO
ALTER TABLE [dbo].[PARTICIPATE]  WITH CHECK ADD FOREIGN KEY([season_id])
REFERENCES [dbo].[SEASONS] ([season_id])
GO
ALTER TABLE [dbo].[PERSONS]  WITH CHECK ADD FOREIGN KEY([fonction_id])
REFERENCES [dbo].[FONCTIONS] ([fonction_id])
GO
USE [master]
GO
ALTER DATABASE [BBIBLIO] SET  READ_WRITE 
GO
